### ISSUE TITLE
Description of the output file?

### ISSUE THREAD

**Issue by meiyang12** [tjgu/miTAR#2]
Hi, I have run this pipeline successfully and got the result, but I don't know how to read it.

```
>hsa-miR-22-3p|1_long|2|4|0.9964378
UGUCAAGAAGUUGACCGUCGAANNNNUGCCAUGGAAUUCCCUCCUGAGUGCCCCACUUCUGGCCACAUCAGCCCCACAG
>hsa-miR-22-3p|1_long|2|14|0.9558402
UGUCAAGAAGUUGACCGUCGAANNNNCUGCUUUGAGCUACAGGACAAAGGCUGACAGACUCACUGGGAAGCUCCCACCC
>hsa-miR-22-3p|2_long|2|0|0.86323965
UGUCAAGAAGUUGACCGUCGAANNNNGGGUUGGCCCCUGGAGGGUCAGGGGACCAUCUUCUUAUUCCCUCUUUUCUCAU
```
1) '2|4|0.9964378', what do these results mean?
2) the FASTA sequence is 80bp length, and what do this sequence mean?

Thank you!

**Comment by tjgu** [comment]
Good morning,
Here are the explanations (take the first case as an example):
*hsa-miR-22-3p|1_long* is the miRNAID|geneID
* 2* is the total number of target site identified at the target location
in one gene. Such as two miRNA target sites were identified in 1_long gene.
*4* is the number of target sites tested. Here shows the 4th target site
result.
*0.9964378* is the probability of the prediction for this specific target
site. The larger number the more confident this site is a target site.
 The results summary has the same meaning. Such as for the first row in the
summary.
The sequence before NNNN is the miRNA sequence and after is the target site
sequence.
 Please feel free to let me know if you have additional questions.

**Comment by meiyang12** [comment]
Thanks for your kind response! In the result, I find that each miRNA has target sites in each gene, this means each miRNA targets all genes. This is unusual. Or I need to filter the results by the probability of the prediction for each specific target site. Maybe sites with only 1.0 could be selected?

**Comment by tjgu** [comment]
Yes. You can do that. The other suggestion is that you can replace the
current model with the  miTAR1_CNN_BiRNN_b30_lr0.005_dout0.2.h5
<https://github.com/tjgu/miTAR/blob/master/scripts_data_models/results/miTAR1_CNN_BiRNN_b30_lr0.005_dout0.2.h5>
which
is more conservative. If less targets are obtained, you can change the
prediction probability to 0.9 or select the targets that have at least two
miRNA target sites or have two target sites from one miRNA.

**Comment by meiyang12** [comment]
Thanks a lot! Best regards.
